### ISSUE TITLE
Hi, how use your spring-security-mongo

### ISSUE THREAD

**Issue by max-dicson-cf** [caelwinner/spring-security-mongo#11]
Hello, I need to implement Oauth2 with MongoDB, but I have not seen updated information with Spring 5 (Spring boot 2.x) So I came across your Repository, I see that it has a library, but it does not have any Security Point, Why He asks me if he can help me with an example to use his library that he has built.

Greetings and thanks in advance

**Comment by caelwinner** [comment]
have a look to this library where I provide a way to setting up the default spring oauth server features.

https://github.com/caelwinner/base-auth2-server

just follow the README file

**Comment by caelwinner** [comment]
Remember that the intention of tis library is to provides all the repos and services necessary to configure your oauth2 server using spring security. It does not provides any configuration by as I mentioned in my previous comment base-auth2-server is default config using this library and allows you customise the login page etc.
