### ISSUE TITLE
oauth2 Client Example is needed

### ISSUE THREAD

**Issue by atul10010** [caelwinner/spring-security-mongo#13]
Hi Cael,

I am very new to spring security and mongo db.

I have found the base auth server example of yours.

Can you provide one example of Oauth2 client with your library?

It would be a great help. TIA

**Comment by caelcs** [comment]
I dont have an example of the client because is all http requests. But you can have a look to the integration tests in base-oauth2-server repo. There you can find exactly the request for each flow.

https://github.com/caelcs/base-auth2-server/blob/master/src/test/java/uk/co/caeldev/base/auth2/AuthorizationServerIntegrationTest.java

Hope this help.

**Comment by caelcs** [comment]
so far the spring security mongo lib provides impl to setup a Oatuh2 Server using Spring.
base oauth2 server is a template for your server which use the other one.

**Comment by atul10010** [comment]
Hi Cael,

My end motive is to create library, so that i can able to login with facebook or google while using mongo as repository.

if you can help me out with this, that would be a great help

**Comment by caelcs** [comment]
I see. Just keep in mind this. The oauth server gives you all the oauth2
flows. One of the great things about spring security is that gives you the
option of defining other oauth 2 servers like google or facebook out the
box.
You just need to configure the server to do so.

I guess that I am trying to understand is what the client library will do.
What is the idea that you have in mind?

**Comment by atul10010** [comment]
Correct, as I mentioned, i am a beginner to spring security and mongo,
and I am looking for the same, i.e. define an oauth2 server for facebook google while using mongo as repository.

**Comment by atul10010** [comment]
As you mentioned, "You just need to configure the server to do so." could you please, provide help me to achieve this with mongo as repository
