### ISSUE TITLE
MongoTemplate remove

### ISSUE THREAD

**Issue by gabac** [caelwinner/spring-security-mongo#2]
According to the documentation you also have to use the class to remove something from the mongo db if you use the Query: http://docs.spring.io/spring-data/mongodb/docs/current/api/org/springframework/data/mongodb/core/MongoTemplate.html#remove-org.springframework.data.mongodb.core.query.Query-java.lang.Class-

Actual:
```Java
@Override
    public boolean deleteByTokenId(final String tokenId) {
        final Query query = Query.query(Criteria.where(ID).is(tokenId));
        final WriteResult removeResult = mongoTemplate.remove(query);
        return removeResult.getN() == 1;
    }
```

Expected
```Java
@Override
    public boolean deleteByTokenId(final String tokenId) {
        final Query query = Query.query(Criteria.where(ID).is(tokenId));
        final WriteResult removeResult = mongoTemplate.remove(query, MongoOAuth2AccessToken.class);
        return removeResult.getN() == 1;
    }
```

**Comment by caelwinner** [comment]
you are correct. I will fix that and write a test for that scenario.
Thx

**Comment by caelwinner** [comment]
I pushed the fix. I did not release a new version but you can use the snapshot version
0.1.10-SNAPSHOT. If you have a moment could you please test it? So I can close the issue.

**Comment by gabac** [comment]
Works fine with 0.1.10-SNAPSHOT
