### ISSUE TITLE
Salting of user password

### ISSUE THREAD

**Issue by gabac** [caelwinner/spring-security-mongo#3]
At the moment there is no support for salting a user's hashed password.

Do you think about supporting it?

**Comment by caelwinner** [comment]
At the moment Spring Security provides an out of the box solution for that. At the moment this library is using NoOpPasswordEncoder implementation but you can use BCryptPasswordEncoder which support Salted password hash.

just declare a bean like this to override the default one.

```
@Bean
@Primary
public PasswordEncoder passwordEncoder() {
       return new BCryptPasswordEncoder();
}
```
