### ISSUE TITLE
Which collection should we create Mongo User json into ?

### ISSUE THREAD

**Issue by peterkhang** [caelwinner/spring-security-mongo#5]
I want to create Mongo User json Document.

Then I don't know the collection where I should insert the Mongo User document.

Please let me know about this.

Thank you!!!

**Comment by caelwinner** [comment]
there is a collection called user. There are two ways how to find this. First have a look the mapping in the domain classes in the project. Or second when you start the app it create the collections if there are not there. Hope this answer your question.

**Comment by peterkhang** [comment]
p{margin-top:0;margin-bottom:0}
    


    

I'll check it as your comments.

Thank you for your response !!!



--------- 원본 메일 ---------

    
        보낸사람: Cael <notifications@github.com>
        받는사람: caelwinner/spring-security-mongo <spring-security-mongo@noreply.github.com>
        
            참조: peterkhang <mgkaki@daum.net>, Author <author@noreply.github.com>
        
        날짜: 17.08.23 18:17 GMT +0900
        제목: Re: [caelwinner/spring-security-mongo] Which collection should we create Mongo User json into ? (#5)
        
        
    
    
        there is a collection called user. There are two ways how to find this. First have a look the mapping in the domain classes in the project. Or second when you start the app it create the collections if there are not there. Hope this answer your question.
