### ISSUE TITLE
Lack of information on how to use this library

### ISSUE THREAD

**Issue by Repulser** [caelwinner/spring-security-mongo#6]
Im trying to use this library and am failing to understand how to use the token store, any insight would be much appreciated.

**Comment by caelwinner** [comment]
Well no much to do... just need two things... annotate your Main Spring Boot application class and then make sure that you have the properties required.

You can have a look to this integration test to see how it works.

https://github.com/caelwinner/spring-security-mongo/blob/master/src/test/java/uk/co/caeldev/springsecuritymongo/MongoClientDetailsServiceIntegrationTest.java

**Comment by caelwinner** [comment]
and one more thing, this library provides you all the beans that you may need to configure your different repositories like store, client credentials etc.
If you want to know how to configure the Spring OAuth2 using this library you can look at the project in my oath2-server and have a look to the spring oauth2 doc.

**Comment by Repulser** [comment]
By looking at the Oauth 2 server code, it seems that MongoTokenStore should be a bean?
Though Ive added the `@EnableMongoSecurity` annotation and still get 
```Parameter 1 of constructor in catalogue.mobile.AuthorizationServerConfig required a bean of type 'uk.co.caeldev.springsecuritymongo.MongoTokenStore' that could not be found.```

**Comment by caelwinner** [comment]
Hello have you added the properties ? Because that could be the only reason why the bean is not in the application context

**Comment by Repulser** [comment]
That was it!! thanks a lot, I added them and everything started working, one last question: is there a way to use my own mongo client and authenticate on my own?

**Comment by caelwinner** [comment]
I dont know what you mean by that but so far this library is like an
extension for Spring Security to use mongo instead of JDBC. there is no
spring logic regarding to authentication.

**Comment by caelwinner** [comment]
you can always override the mongo client provided by defining your own and using the @Primary annotation 👍

**Comment by Repulser** [comment]
I meant authenticating with mongo, the `@Primary` worked perfectly, thanks! though theres still the need to define the properties, is there a way to avoid this or should i just pseudo-define them?

**Comment by caelwinner** [comment]
unfortunately it is mandatory for this version just because without those
properties the default implementation wont work...

**Comment by caelwinner** [comment]
for the next version I could add the validation at the mongo client level
and see how that works.

**Comment by caelwinner** [comment]
What kind of feature are you trying to implement that the default Mongo
client does not support?

**Comment by Repulser** [comment]
Nothing really, im just using mongo for other things and would like to share the client, aswell as using different methods of authentication....

**Comment by caelwinner** [comment]
I have release version 2.0.0 adding only the Mongo Client when the properties has been set. Can I close this issue?
